[mgr]
ratio = [1, 7, 0]
show_hidden = true

[opener]
edit = [
  { run = 'nvim --server "/tmp/nvim-socket-$ZELLIJ_SESSION_NAME" --remote-expr "luaeval(\"Yazi.open(_A)\", \"$1\")"', desc = "Open in nvim" },
]

[open]
rules = [
  { mime = "text/*", use = "edit" },
  { url = "*.json", use = "edit" },
  { url = "*.jsoc", use = "edit" },
]
